import { defineConfig } from 'oxlint'

export default defineConfig({
  ignorePatterns: [
    '.agent/**',
    '.agents/**',
    '.claude/**',
    '.codex/**',
    '.continue/**',
    '.cursor/**',
    '.gemini/**',
    '.opencode/**',
    '.pi/**',
    '.roo/**',
    '.windsurf/**',
    'dist/**',
    '.turbo/**',
    'scripts/**',
    'plugins/harness-pi/src/pi/oru-pi-extension.mjs',
    'tools/oxlint/anti-slop/**',
    'apps/oru/src/components/**',
    'apps/oru/src/lib/icons.ts',
    'apps/oru/src/lib/utils.ts',
    'apps/oru/e2e/**',
    'apps/oru/playwright.config.ts',
  ],
  jsPlugins: [
    { name: 'anti-slop', specifier: './tools/oxlint/anti-slop/index.ts' },
    { name: 'anti-slop-effect', specifier: './tools/oxlint/anti-slop/effect/index.ts' },
  ],
  options: {
    typeAware: true,
    typeCheck: true,
  },
  plugins: ['typescript', 'oxc'],
  rules: {
    'oxc/no-accumulating-spread': 'error',
    'anti-slop/no-array-filter-map': 'error',
    'anti-slop/no-reduce-accumulator-copy': 'error',
    'anti-slop/no-chained-type-assertions': 'error',
    'anti-slop/no-conditional-empty-object-spread': 'error',
    'anti-slop/no-known-value-widening': 'error',
    'anti-slop/no-module-mocking': 'error',
    'anti-slop/no-object-parameters': 'error',
    'anti-slop/no-reflect-apply': 'error',
    'anti-slop/no-reflect-get': 'error',
    'anti-slop/no-runtime-typeof': 'error',
    'anti-slop/no-shape-in-symbol-names': 'error',
    'anti-slop/no-unknown-parameters': 'error',
    'anti-slop/no-unknown-returns': 'error',
    'anti-slop/no-unknown-type-aliases': 'error',
    'anti-slop/no-unsafe-dictionary-type': 'error',
    'anti-slop/no-widen-then-assert': 'error',
    'anti-slop/require-safety-comment-for-type-assertion': 'error',
    'anti-slop-effect/no-effect-internal-tags': 'error',
    'anti-slop-effect/no-error-constructor': 'error',
    'anti-slop-effect/no-manual-tag-equality': 'error',
    'anti-slop-effect/no-manual-tagged-object': 'error',
    'anti-slop-effect/no-service-constructor-imports': 'error',
    'no-unused-vars': [
      'error',
      {
        argsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
        destructuredArrayIgnorePattern: '^_',
        varsIgnorePattern: '^_',
      },
    ],
    'typescript/no-explicit-any': 'error',
  },
})
